name: mission-data-recorder-backend

on:
  push:
    branches: main
    paths:
      - mission-data-recorder-backend/**

jobs:
  tii-mission-data-recorder-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...
        working-directory: ./mission-data-recorder-backend/

      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build tii-mission-data-recorder-backend image and push
        uses: docker/build-push-action@v2
        with:
          context: ./mission-data-recorder-backend/
          file: ./mission-data-recorder-backend/Dockerfile
          push: true
          tags: ghcr.io/tiiuae/tii-mission-data-recorder-backend:latest
